# Generated by Django 3.2 on 2022-12-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm',
            name='tag',
            field=models.CharField(choices=[('talk', 'TALK'), ('issue', 'ISSUE'), ('project', 'PROJECT'), ('connect', 'CONNECT')], max_length=7, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='comm',
            name='title',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
